name: End-to-end tests
on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Cypress
        run: npm run test:report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mochawesome-report
          path: mochawesome-report/
          retention-days: 15
