name: End-to-end tests
on:
  push:
    branches:
      - main

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Cypress
        run: npm run test:report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mochawesome-report
          path: mochawesome-report/
          retention-days: 15

  slack_success_result:
    needs: [cypress-e2e]
    name: Slack Notification
    runs-on: ubuntu-latest
    if: $${{ success() }}
    steps:
      - uses: actions/checkout@v2
      - name: Send success message GitHub
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: failed
