name: End-to-end tests
on:
  push:
jobs:
  cypress-e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mochawesome-report
          path: mochawesome-report/
          retention-days: 15
